// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcb2gMkTWYdLt_PZKQ6Y6fQUXdty_0TZQ',
    appId: '1:714497985050:web:45785497bcd97b2d555fa3',
    messagingSenderId: '714497985050',
    projectId: 'mogur-4d3d4',
    authDomain: 'mogur-4d3d4.firebaseapp.com',
    databaseURL: 'https://mogur-4d3d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mogur-4d3d4.firebasestorage.app',
    measurementId: 'G-F9HZTK99LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-63HWQYREp46vIK7IoPUd8jEGpk07WWY',
    appId: '1:714497985050:android:b3fb414e6de032e2555fa3',
    messagingSenderId: '714497985050',
    projectId: 'mogur-4d3d4',
    databaseURL: 'https://mogur-4d3d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mogur-4d3d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASuUjFonDFSBf8SpkTOUexgevm0OgAxb0',
    appId: '1:714497985050:ios:1843c77ce6056067555fa3',
    messagingSenderId: '714497985050',
    projectId: 'mogur-4d3d4',
    databaseURL: 'https://mogur-4d3d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mogur-4d3d4.firebasestorage.app',
    iosBundleId: 'com.example.mogur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASuUjFonDFSBf8SpkTOUexgevm0OgAxb0',
    appId: '1:714497985050:ios:1843c77ce6056067555fa3',
    messagingSenderId: '714497985050',
    projectId: 'mogur-4d3d4',
    databaseURL: 'https://mogur-4d3d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mogur-4d3d4.firebasestorage.app',
    iosBundleId: 'com.example.mogur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcb2gMkTWYdLt_PZKQ6Y6fQUXdty_0TZQ',
    appId: '1:714497985050:web:d4d5a2fec2bf305a555fa3',
    messagingSenderId: '714497985050',
    projectId: 'mogur-4d3d4',
    authDomain: 'mogur-4d3d4.firebaseapp.com',
    databaseURL: 'https://mogur-4d3d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mogur-4d3d4.firebasestorage.app',
    measurementId: 'G-1JSRN4WCES',
  );
}
